#!/bin/bash

JIRA_URL="https://__URL_TO_YOUR_JIRA_INSTANCE__/browse/"
# example: https://jira.google.com/browse/"

function print {
	F_MESSAGE=$1
	F_COLOR=$2
	echo -e "${F_COLOR}${F_MESSAGE}\033[00m"
}

function open_url {
	F_URL=$1
	if [  $BROWSER ]; then
		$BROWSER $F_URL
	elif which xdg-open > /dev/null; then
		xdg-open $F_URL
	elif which gnome-open > /dev/null; then
		gnome-open $F_URL
	elif which open > /dev/null; then
		open $F_URL
	elif which x-www-browser > /dev/null; then	
		x-www-browser $F_URL
	elif which lynx > /dev/null; then	
		lynx $F_URL
	else
		print "Could not detect the web browser to use!" "\033[1;31m"
	fi
}

BRANCH=`git rev-parse --abbrev-ref HEAD 2>/dev/null`
if [ "$BRANCH" ]
then
	JIRA_ISSUE=`echo "$BRANCH" | sed -E -n "s/^.+\/([a-bA-Z]+-[0-9]+).*$/\1/p"`
	if [ $JIRA_ISSUE ]
	then
		URL="${JIRA_URL}${JIRA_ISSUE}"
		echo -e "\033[1;32mGo to >> \033[4m${URL}\033[24m\033[00m" 
		open_url "$URL"
	else
		print "JIRA issue not matched!" "\033[1;31m"
	fi
else
	print "GIT Repository not found!" "\033[1;31m"
fi


